limits:
  daily: 60
  flood: 5
messages:
  send: 3
threads:
  send: 2
  receive: 1
reaction:
  send: 2
  receive: 2
reactions:
  atena: 0.1
  send: 2
  receive:
    positive: 3
    negative: -1
github:
  issue: 2
  review: 3
  pull_request: 5
  merged_pull_request: 9
disqus:
  comment: 5
blog:
  post: 30
  comment: 5
inactive:
  mindays: 14
  value: -2
linkedin: 3
team:
  interview: 5
  approved: 7
  allocated: 9
referral: 3
